### PR TITLE
Fixed XMath CPU unit tests by using predefined preprocessor symbols.

### PR DESCRIPTION
**Pull request by MoFtZ**
Some of the XMath CPU unit tests would fail because the unit test uses `MathF.Asin` and ILGPU was using `(float)Math.Asin`.

After switching to the predefined preprocessor symbols, the issue goes away.

Depends on https://github.com/m4rs-mt/ILGPU/pull/264.

### CODE REVIEW

**Comment by MoFtZ** [comment]
Tried to updated ILGPU submodule to include changes from https://github.com/m4rs-mt/ILGPU/pull/264.

Failed because the ILGPU.Algorithms unit test projects rely on ILGPU projecs, which updated their test frameworks.

Now depends on https://github.com/m4rs-mt/ILGPU.Algorithms/pull/54.

**Comment by MoFtZ** [comment]
Abandoned #54 and rolled into one PR - this one.

**Comment by MoFtZ** [comment]
The ReorderExtensionTests unit tests are failing.

Looks like a regression as part of changes for https://github.com/m4rs-mt/ILGPU/pull/262.

It appears that the "transformers" have no fields, but a size of 1. The code for remapping field indices then generates an array of of bounds exception.

**Comment by MoFtZ** [comment]
Depends on fix for regression in field access of empty structures (https://github.com/m4rs-mt/ILGPU/pull/267).

**Comment by MoFtZ** [comment]
Updated all dependencies.

**Review by m4rs-mt — APPROVED** [review]

**Pull request merged**
